name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      tag:
        description: 'Git Tag to checkout'
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:

      - uses: actions/checkout@v3
        with:
          repository: 'khayyamov/sing-box'
          path: 'box'
          ref: ${{ github.event.inputs.tag }}

      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.20'

      - name: Setup Gomobile
        run: |
          cd box
          make lib_install
          gomobile init

      - name: Build xcframework
        run: |
          cd box
          go run ./cmd/internal/build_libbox -target=android
          ls

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          body: 'Compiled from source tag: ${{ github.event.inputs.tag }}'
          files: box/libbox.aar