name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
      tag:
        description: 'Git Tag to checkout'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'khayyamov/sing-box'
          path: 'box'
          ref: ${{ github.event.inputs.tag }}

      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ^1.22

      - name: Run Shell Script
        run: |
          #!/bin/bash
          
          whereis go
          go version
          mv request.txt /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/request.go
          cat /opt/hostedtoolcache/go/1.22.4/x64/src/net/http/request.go
          

      - name: Setup Gomobile
        run: |
          cd box
          make lib_install
          gomobile init

      - name: Build aar
        run: |
          echo $ANDROID_HOME
          ls $ANDROID_HOME/ndk
          cd box
          go run ./cmd/internal/build_libbox -target=android
          ls
          echo $PWD


      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/xray-singbox-aar-lib-android/xray-singbox-aar-lib-android/box/libbox.aar
          tag: ${{ github.ref }}
          file_glob: true